
version: 1.0.{build}
image: Visual Studio 2015

environment:
  SPOROOT: 'C:\projects\netmf-interpreter\build-tools'

# Tool Download
# old
# Start-FileDownload "http://netmf.github.io/downloads/build-tools.zip"
# Import-Module ".\appveyor\PS-Zip\PS-Zip.psm1" -Force
# .\appveyor\install.ps1
# new
# Import-Module .\tools\scripts\Build-netmf.psm1
# Invoke-WebRequest -UseBasicParsing -Uri "http://netmf.github.io/downloads/build-tools.zip" | Expand-Stream -Destination $SPOROOT
# CLR Build
# https://github.com/NETMF/netmf-interpreter/issues/378
# https://github.com/NETMF/netmf-interpreter/blob/34a92c3d79d3d1c48440dc32f88d5b81095311a4/Framework/Tools/CreateCLRDefines.proj
# MSbuild dotnetmf.proj /t:GenerateCLRDefines
# MMU use?(ARM7/9)
# https://github.com/NETMF/netmf-interpreter/wiki/Hardware%20Layer
# Import-Module ".\appveyor\PS-Zip\PS-Zip.psm1" -Force
# .\appveyor\install.ps1
# gcc toolchain
# old (2015)
# Start-FileDownload "https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-win32.zip"
# new (2016)
# Start-FileDownload "https://launchpad.net/gcc-arm-embedded/5.0/5-2016-q2-update/+download/gcc-arm-none-eabi-5_4-2016q2-20160622-win32.zip"
# CMSIS Set?
# Start-FileDownload "https://codeload.github.com/ARM-software/CMSIS/zip/master"
install:
- ps: >-
    Start-FileDownload "https://github.com/NETMF/netmf-interpreter/releases/download/NETMFCryptoLibraries/NetMFCryptoLibs.msi"
    
    Start-FileDownload "https://launchpad.net/gcc-arm-embedded/4.9/4.9-2015-q3-update/+download/gcc-arm-none-eabi-4_9-2015q3-20150921-win32.zip"
    
    Start-FileDownload "http://netmf.github.io/downloads/build-tools.zip"
    
    Start-FileDownload "https://github.com/NETMF/netmf-interpreter/releases/download/v4.4-RTW-20-Oct-2015/MicroFrameworkSDK.MSI"
    
    Import-Module ".\appveyor\PS-Zip\PS-Zip.psm1" -Force
    
    .\appveyor\install.ps1
    
    msiexec.exe NetMFCryptoLibs.msi /VERYSILENT /NORESTART
    
    msiexec.exe MicroFrameworkSDK.MSI /VERYSILENT /NORESTART


# NG : 
# MSbuild dotnetmf.proj /t:GenerateCLRDefines
# netmfvs2015.msi /VERYSILENT /NORESTART
# old
# setenv_gcc 5.2.1 C:\projects\gcc-arm-none-eabi
# new
# setenv_gcc 5.4.1 C:\projects\gcc-arm-none-eabi
# current?
# setenv_gcc 4.9.3 C:\projects\gcc-arm-none-eabi
# build_sdk.cmd
# cd Solutions\ToppersHRP2onEV3
# cd Solutions\MBED_GR_PEACH_Native
# dir "C:\projects"
# dir "C:\projects\gcc-arm-none-eabi"
# dir "C:\projects\netmf-interpreter"
# cd Solutions\MBED_GR_PEACH_Native
build_script:
- cmd: >-
    setenv_gcc 4.9.3 C:\projects\gcc-arm-none-eabi
    
    cd Solutions\MBED_GR_PEACH_Native
    
    MSbuild dotnetmf.proj /t:rebuild /p:flavor=release /p:memory=flash

artifacts:
- path: BuildOutput\RZA1\GCC4.9\le\FLASH\release\MBED_GR_PEACH\bin\tinyclrnbl.bin
  name: Release
# - path: BuildOutput\RZA1\GCC4.9\le\FLASH\release\MBED_GR_PEACH\bin\tinyclr.bin
#   name: Release

