
version: 1.0.{build}
image: Visual Studio 2015

# Tool Download
# old
# Start-FileDownload "http://netmf.github.io/downloads/build-tools.zip"
# Import-Module ".\appveyor\PS-Zip\PS-Zip.psm1" -Force
# .\appveyor\install.ps1
# new
# Import-Module .\tools\scripts\Build-netmf.psm1
# Invoke-WebRequest -UseBasicParsing -Uri "http://netmf.github.io/downloads/build-tools.zip" | Expand-Stream -Destination $SPOROOT
# CLR Build
# https://github.com/NETMF/netmf-interpreter/issues/378
# https://github.com/NETMF/netmf-interpreter/blob/34a92c3d79d3d1c48440dc32f88d5b81095311a4/Framework/Tools/CreateCLRDefines.proj
# MSbuild dotnetmf.proj /t:GenerateCLRDefines
install:
- ps: >-
    Start-FileDownload "https://github.com/NETMF/netmf-interpreter/releases/download/NETMFCryptoLibraries/NetMFCryptoLibs.msi"
    
    Start-FileDownload "https://launchpad.net/gcc-arm-embedded/5.0/5-2015-q4-major/+download/gcc-arm-none-eabi-5_2-2015q4-20151219-win32.zip"
    
    Import-Module .\tools\scripts\Build-netmf.psm1
    
    Invoke-WebRequest -UseBasicParsing -Uri "http://netmf.github.io/downloads/build-tools.zip" | Expand-Stream -Destination $SPOROOT


build_script:
- cmd: >-
    MSbuild dotnetmf.proj /t:GenerateCLRDefines
    
    build_sdk.cmd
	
    setenv_gcc 5.2.1 C:\projects\gcc-arm-none-eabi
	
    cd Solutions\ToppersHRP2onEV3
	
    MSbuild dotnetmf.proj /t:rebuild /p:flavor=release;memory=flash
	
    msiexec.exe NetMFCryptoLibs.msi /VERYSILENT /NORESTART
	
    netmfvs2015.msi /VERYSILENT /NORESTART


artifacts:
- path: netmfvs2015.msi
  name: netmfvs2015


