
version: 1.0.{build}
image: Visual Studio 2015

branches:
  only:
  - dev
  - grpeach_on_Toppers


environment:
  matrix:
    - SPOROOT: 'C:\projects\netmf-interpreter\build-tools'
      GCC_VERSION: '4.9.3'
      GCC_TOOLS: 'C:\projects\gcc-arm-none-eabi'
      SOLUTION_PATH  : 'MBED_GR_PEACH'
      OUTPUT_MODULE  : 'RZA1'
      OUTPUT_MODULE2 : 'GCC4.9\'
      MEMORY_TYPE    : 'FLASH'
      FLAVOR_TYPE    : 'Release'
      # OUTPUT_BINARY  : 'tinyclr.bin'
      OUTPUT_BINARY_FOLDER  : 'BuildOutput\%OUTPUT_MODULE%\%OUTPUT_MODULE2%le\%MEMORY_TYPE%\%FLAVOR_TYPE%\MBED_GR_PEACH\bin'
      # Dummy
      OUTPUT_BINARY_FOLDER2 : 'BuildOutput'


#     - SPOROOT: 'C:\projects\netmf-interpreter\build-tools'
#       GCC_VERSION: '4.9.3'
#       GCC_TOOLS: 'C:\projects\gcc-arm-none-eabi'
#       SOLUTION_PATH  : 'MBED_GR_PEACH_Native'
#       OUTPUT_MODULE  : 'RZA1'
#       OUTPUT_MODULE2 : 'GCC4.9\'
#       MEMORY_TYPE    : 'FLASH'
#       FLAVOR_TYPE    : 'Release'
#       # OUTPUT_BINARY  : 'tinyclrnbl.bin'
#       OUTPUT_BINARY_FOLDER  : 'BuildOutput\%OUTPUT_MODULE%\%OUTPUT_MODULE2%le\%MEMORY_TYPE%\%FLAVOR_TYPE%\MBED_GR_PEACH\bin'
#       # Dummy
#       OUTPUT_BINARY_FOLDER2 : 'BuildOutput'


#     - SPOROOT: 'C:\projects\netmf-interpreter\build-tools'
#       GCC_VERSION: '4.9.3'
#       GCC_TOOLS: 'C:\projects\gcc-arm-none-eabi'
#       SOLUTION_PATH  : 'Windows2'
#       OUTPUT_MODULE  : 'Windows'
#       OUTPUT_MODULE2 : ''
#       MEMORY_TYPE    : 'RAM'
#       FLAVOR_TYPE    : 'Release'
#       # OUTPUT_BINARY  : '..\..\..\..\ANY_MEDIA\Release\*'
#       OUTPUT_BINARY_FOLDER  : 'BuildOutput\%OUTPUT_MODULE%\%OUTPUT_MODULE2%le\ANY_MEDIA\%FLAVOR_TYPE%\lib'
#       OUTPUT_BINARY_FOLDER2 : 'BuildOutput\%OUTPUT_MODULE%\%OUTPUT_MODULE2%le\RAM\%FLAVOR_TYPE%\Windows2\lib'


    # Debug
    - SPOROOT: 'C:\projects\netmf-interpreter\build-tools'
      GCC_VERSION: '4.9.3'
      GCC_TOOLS: 'C:\projects\gcc-arm-none-eabi'
      SOLUTION_PATH  : 'Windows'
      OUTPUT_MODULE  : 'Windows'
      OUTPUT_MODULE2 : ''
      MEMORY_TYPE    : 'RAM'
      FLAVOR_TYPE    : 'Debug'
      # OUTPUT_BINARY  : '..\..\..\..\ANY_MEDIA\Debug\*'
      OUTPUT_BINARY_FOLDER  : 'BuildOutput\%OUTPUT_MODULE%\%OUTPUT_MODULE2%le\ANY_MEDIA\%FLAVOR_TYPE%\lib'
      OUTPUT_BINARY_FOLDER2 : 'BuildOutput\%OUTPUT_MODULE%\%OUTPUT_MODULE2%le\RAM\%FLAVOR_TYPE%\Win32\lib'


    # Release
    - SPOROOT: 'C:\projects\netmf-interpreter\build-tools'
      GCC_VERSION: '4.9.3'
      GCC_TOOLS: 'C:\projects\gcc-arm-none-eabi'
      SOLUTION_PATH  : 'Windows'
      OUTPUT_MODULE  : 'Windows'
      OUTPUT_MODULE2 : ''
      MEMORY_TYPE    : 'RAM'
      FLAVOR_TYPE    : 'Release'
      # OUTPUT_BINARY  : '..\..\..\..\ANY_MEDIA\Release\*'
      OUTPUT_BINARY_FOLDER  : 'BuildOutput\%OUTPUT_MODULE%\%OUTPUT_MODULE2%le\ANY_MEDIA\%FLAVOR_TYPE%\lib'
      OUTPUT_BINARY_FOLDER2 : 'BuildOutput\%OUTPUT_MODULE%\%OUTPUT_MODULE2%le\RAM\%FLAVOR_TYPE%\Win32\lib'


install:
- ps: >-
    Start-FileDownload "https://github.com/NETMF/netmf-interpreter/releases/download/NETMFCryptoLibraries/NetMFCryptoLibs.msi"

    Start-FileDownload "http://netmf.github.io/downloads/build-tools.zip"

    Start-FileDownload "https://github.com/NETMF/netmf-interpreter/releases/download/v4.4-RTW-20-Oct-2015/MicroFrameworkSDK.MSI"

    Start-FileDownload "https://github.com/NETMF/netmf-interpreter/releases/download/v4.4-RTW-20-Oct-2015/NetMFVS14.vsix"

    msiexec.exe /i NetMFCryptoLibs.msi /quiet /norestart

    msiexec.exe /i MicroFrameworkSDK.MSI /quiet /norestart

    .\install-vsix-appveyor.ps1

    Import-Module ".\appveyor\PS-Zip\PS-Zip.psm1" -Force

    .\appveyor\install.ps1


build_script:
- cmd: >-
    timeout 60

    MSbuild DeviceCode\Targets\Native\Interop\ManagedCode\CQ_NETMF_CQ_FRK_FM3_Hardware\CQ_NETMF_CQ_FRK_FM3_Hardware.sln /p:Configuration=%FLAVOR_TYPE%

    MSbuild DeviceCode\Targets\Native\Interop\ManagedCode\CQ_NETMF_CQFM3DUINO_Hardware\CQ_NETMF_CQ_FRK_FM3_Hardware.sln /p:Configuration=%FLAVOR_TYPE%

    MSbuild DeviceCode\Targets\Native\Interop\ManagedCode\CQ_NETMF_LCD\CQ_NETMF_LCD.sln /p:Configuration=%FLAVOR_TYPE%

    MSbuild DeviceCode\Targets\Native\Interop\ManagedCode\CQ_NETMF_LEDMATRIX\CQ_NETMF_LEDMATRIX.sln /p:Configuration=%FLAVOR_TYPE%

    MSbuild DeviceCode\Targets\Native\Interop\ManagedCode\CQ_NETMF_LEDMATRIXAF\CQ_NETMF_LEDMATRIXAF.sln /p:Configuration=%FLAVOR_TYPE%

    MSbuild DeviceCode\Targets\Native\Interop\ManagedCode\CQ_NETMF_MP3\CQ_NETMF_MP3.sln /p:Configuration=%FLAVOR_TYPE%

    MSbuild DeviceCode\Targets\Native\Interop\ManagedCode\CQ_NETMF_SD\CQ_NETMF_SD.sln /p:Configuration=%FLAVOR_TYPE%

    MSbuild DeviceCode\Targets\Native\Interop\ManagedCode\CQ_NETMF_UTIL\CQ_NETMF_UTIL.sln /p:Configuration=%FLAVOR_TYPE%

    MSbuild DeviceCode\Targets\Native\Interop\ManagedCode\Microsoft_SPOT_HAL\Microsoft_SPOT_HAL.sln /p:Configuration=%FLAVOR_TYPE%

    setenv_gcc %GCC_VERSION% %GCC_TOOLS%

    cd Solutions\%SOLUTION_PATH%

    MSbuild dotnetmf.proj /t:rebuild /p:flavor=%FLAVOR_TYPE% /p:memory=%MEMORY_TYPE%


after_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    echo %OUTPUT_BINARY_FOLDER%

    echo %APPVEYOR_BUILD_FOLDER%

    7z a deploy.zip %APPVEYOR_BUILD_FOLDER%\%OUTPUT_BINARY_FOLDER%\*.*

    7z a deploy.zip %APPVEYOR_BUILD_FOLDER%\%OUTPUT_BINARY_FOLDER2%\*.*


artifacts:
- path: deploy.zip
  name: Release
# BuildOutput\%OUTPUT_MODULE%\%OUTPUT_MODULE2%le\%MEMORY_TYPE%\%FLAVOR_TYPE%\MBED_GR_PEACH\bin\%OUTPUT_BINARY%
# - path: BuildOutput\RZA1\GCC4.9\le\FLASH\release\MBED_GR_PEACH\bin\tinyclr.bin
#   name: Release

