#ifndef _TOPPERS_RTOS_PROCESSOR_SELECTOR_H_
#define _TOPPERS_RTOS_PROCESSOR_SELECTOR_H_ 1
#include "toppers_os.h"

#define PLATFORM_ARM 1 
#define PLATFORM_ARM_OS_PORT 1

#endif //_TOPPERS_RTOS_PROCESSOR_SELECTOR_H_
